### PR TITLE
changed "Ptr" to "CDecl" in ImageSearch()

### PR DESCRIPTION
**Pull request by XRay71**

### CODE REVIEW

**Comment by XRay71** [comment]
Tried using ImageSearch the other day, got a runtime error on the DllCall; this fixed it.

**Comment by iseahound** [comment]
This only occurs on 32-bit windows? Are you on Windows 10/11?

**Comment by iseahound** [comment]
Did some testing - only AHK v2 throws, while AHK v1 works fine.

**Comment by iseahound** [comment]
Thanks. This is fixed now for every function, including, but not limited to, ImageSearch.

**Pull request closed without merging**
